config/routes.rb
Amiral::Application.routes.draw do
  resources :saisons

  

end

app/models/saison.rb
class Saison < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/saisons_controller.rb
class SaisonsController < ApplicationController
  before_action :set_saison, only: [:show, :edit, :update, :destroy]

  # GET /saisons
  # GET /saisons.json
  def index
    @saisons = Saison.all
  end

  # GET /saisons/1
  # GET /saisons/1.json
  def show
  end

  # GET /saisons/new
  def new
    @saison = Saison.new
  end

  # GET /saisons/1/edit
  def edit
  end

  # POST /saisons
  # POST /saisons.json
  def create
    @saison = Saison.new(saison_params)

    respond_to do |format|
      if @saison.save
        format.html { redirect_to @saison, notice: 'Saison was successfully created.' }
        format.json { render action: 'show', status: :created, location: @saison }
      else
        format.html { render action: 'new' }
        format.json { render json: @saison.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saisons/1
  # PATCH/PUT /saisons/1.json
  def update
    respond_to do |format|
      if @saison.update(saison_params)
        format.html { redirect_to @saison, notice: 'Saison was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @saison.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saisons/1
  # DELETE /saisons/1.json
  def destroy
    @saison.destroy
    respond_to do |format|
      format.html { redirect_to saisons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saison
      @saison = Saison.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saison_params
      params.require(:saison).permit(:annee, :ligue, :sport)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/saisons_helper.rb
module SaisonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amiral</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/saisons/_form.html.erb
<%= form_for(@saison) do |f| %>
  <% if @saison.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saison.errors.count, "error") %> prohibited this saison from being saved:</h2>

      <ul>
      <% @saison.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :annee %><br>
    <%= f.text_field :annee %>
  </div>
  <div class="field">
    <%= f.label :ligue %><br>
    <%= f.text_field :ligue %>
  </div>
  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saisons/edit.html.erb
<h1>Editing saison</h1>

<%= render 'form' %>

<%= link_to 'Show', @saison %> |
<%= link_to 'Back', saisons_path %>

app/views/saisons/index.html.erb
<h1>Listing saisons</h1>

<table>
  <thead>
    <tr>
      <th>Annee</th>
      <th>Ligue</th>
      <th>Sport</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @saisons.each do |saison| %>
      <tr>
        <td><%= saison.annee %></td>
        <td><%= saison.ligue %></td>
        <td><%= saison.sport %></td>
        <td><%= link_to 'Show', saison %></td>
        <td><%= link_to 'Edit', edit_saison_path(saison) %></td>
        <td><%= link_to 'Destroy', saison, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saison', new_saison_path %>

app/views/saisons/new.html.erb
<h1>New saison</h1>

<%= render 'form' %>

<%= link_to 'Back', saisons_path %>

app/views/saisons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Annee:</strong>
  <%= @saison.annee %>
</p>

<p>
  <strong>Ligue:</strong>
  <%= @saison.ligue %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @saison.sport %>
</p>

<%= link_to 'Edit', edit_saison_path(@saison) %> |
<%= link_to 'Back', saisons_path %>